<Project Sdk="Microsoft.NET.Sdk.Web"><PropertyGroup><TargetFramework>net9.0</TargetFramework><Nullable>enable</Nullable><ImplicitUsings>enable</ImplicitUsings></PropertyGroup><ItemGroup><ProjectReference Include="../GestionProductos.Core/GestionProductos.Core.csproj"/><ProjectReference Include="../GestionProductos.Data/GestionProductos.Data.csproj"/></ItemGroup></Project>
